`timescale 1ns / 1ps
`include "novaDefinitions.vh"
//////////////////////////////////////////////////////////////////////////////////
// Engineer: Noah Arnold
//
// Design Name: NOVA CPU Core
// Module Name: cpuCore
// Project Name: NOVA
// Description:
//   Integrates the NOVA control unit, instruction-fetch path, register file,
//   ALU, status register, and data memory into a complete eight-bit processor.
//////////////////////////////////////////////////////////////////////////////////

module cpuCore (
    input             clk,
    input             reset,

    output            halted,
    output            zeroFlag,
    output            carryFlag,
    output            borrowFlag,
    output     [7:0]  debugProgramAddress,
    output     [15:0] debugInstruction,
    output     [2:0]  debugState,
    output     [7:0]  debugExecutionResult,
    output            debugRegisterWriteEnable,
    output     [2:0]  debugRegisterWriteAddress,
    output     [7:0]  debugRegisterWriteData
);

    // Control signals generated by the multicycle controller.
    wire       pcIncrementEnable;
    wire       pcLoadEnable;
    wire       instructionLoadEnable;
    wire       registerWriteEnable;
    wire       dataMemoryWriteEnable;
    wire       flagWriteEnable;
    wire [2:0] aluOperation;
    wire [1:0] writeBackSelect;

    // Instruction-fetch signals.
    wire [7:0]  programAddress;
    wire [15:0] instructionFromMemory;
    wire [15:0] currentInstruction;

    // Decoded instruction fields.
    wire [3:0] instructionOpcode;
    wire [2:0] destinationAddress;
    wire [2:0] sourceAddressA;
    wire [2:0] sourceAddressB;
    wire [7:0] immediateOrAddress;

    // Register-file and datapath signals.
    wire [2:0] registerReadAddressA;
    wire [2:0] registerReadAddressB;
    wire [7:0] registerReadDataA;
    wire [7:0] registerReadDataB;
    reg  [7:0] registerWriteData;

    // ALU and memory signals.
    wire [7:0] aluResult;
    wire       candidateZeroFlag;
    wire       candidateCarryFlag;
    wire       candidateBorrowFlag;
    reg  [7:0] executionResult;
    wire [7:0] dataMemoryReadData;

    assign instructionOpcode = currentInstruction[15:12];
    assign destinationAddress = currentInstruction[11:9];
    assign sourceAddressA = currentInstruction[8:6];
    assign sourceAddressB = currentInstruction[5:3];
    assign immediateOrAddress = currentInstruction[7:0];

    // ST stores the register encoded in [11:9]. Other register operations read
    // source A from [8:6]. Source B is always encoded in [5:3].
    assign registerReadAddressA =
        (instructionOpcode == `NOVA_OPCODE_ST) ? destinationAddress
                                               : sourceAddressA;
    assign registerReadAddressB = sourceAddressB;

    // Save the ALU result at the end of EXECUTE so it remains stable throughout
    // the following WRITEBACK cycle.
    always @(posedge clk) begin
        if (reset)
            executionResult <= 8'h00;
        else if (flagWriteEnable)
            executionResult <= aluResult;
    end

    // Select which datapath value is written into the destination register.
    always @(*) begin
        case (writeBackSelect)
            `NOVA_WB_ALU:       registerWriteData = executionResult;
            `NOVA_WB_IMMEDIATE: registerWriteData = immediateOrAddress;
            `NOVA_WB_MEMORY:    registerWriteData = dataMemoryReadData;
            `NOVA_WB_REGISTER:  registerWriteData = registerReadDataA;
            default:            registerWriteData = 8'h00;
        endcase
    end

    cu controlUnit (
        .clk(clk),
        .reset(reset),
        .instructionOpcode(instructionOpcode),
        .zeroFlag(zeroFlag),
        .carryFlag(carryFlag),
        .pcIncrementEnable(pcIncrementEnable),
        .pcLoadEnable(pcLoadEnable),
        .instructionLoadEnable(instructionLoadEnable),
        .registerWriteEnable(registerWriteEnable),
        .dataMemoryWriteEnable(dataMemoryWriteEnable),
        .flagWriteEnable(flagWriteEnable),
        .aluOperation(aluOperation),
        .writeBackSelect(writeBackSelect),
        .halted(halted),
        .currentStateDebug(debugState)
    );

    programCounter pc (
        .clk(clk),
        .reset(reset),
        .incrementEnable(pcIncrementEnable),
        .loadEnable(pcLoadEnable),
        .loadAddress(immediateOrAddress),
        .programAddress(programAddress)
    );

    instructionMemory programRom (
        .programAddress(programAddress),
        .instruction(instructionFromMemory)
    );

    instructionRegister instructionReg (
        .clk(clk),
        .reset(reset),
        .loadEnable(instructionLoadEnable),
        .instructionIn(instructionFromMemory),
        .instructionOut(currentInstruction)
    );

    registers registerFile (
        .clk(clk),
        .reset(reset),
        .writeEnable(registerWriteEnable),
        .readAddressA(registerReadAddressA),
        .readAddressB(registerReadAddressB),
        .writeAddress(destinationAddress),
        .writeData(registerWriteData),
        .readDataA(registerReadDataA),
        .readDataB(registerReadDataB)
    );

    alu arithmeticLogicUnit (
        .operandA(registerReadDataA),
        .operandB(registerReadDataB),
        .aluOperation(aluOperation),
        .result(aluResult),
        .zeroFlag(candidateZeroFlag),
        .carryFlag(candidateCarryFlag),
        .borrowFlag(candidateBorrowFlag)
    );

    statusRegister flags (
        .clk(clk),
        .reset(reset),
        .flagWriteEnable(flagWriteEnable),
        .zeroIn(candidateZeroFlag),
        .carryIn(candidateCarryFlag),
        .borrowIn(candidateBorrowFlag),
        .zeroFlag(zeroFlag),
        .carryFlag(carryFlag),
        .borrowFlag(borrowFlag)
    );

    dataMemory dataRam (
        .clk(clk),
        .writeEnable(dataMemoryWriteEnable),
        .address(immediateOrAddress),
        .writeData(registerReadDataA),
        .readData(dataMemoryReadData)
    );

    // Debug outputs will later connect to the Nexys A7 display wrapper.
    assign debugProgramAddress = programAddress;
    assign debugInstruction = currentInstruction;
    assign debugExecutionResult = executionResult;
    assign debugRegisterWriteEnable = registerWriteEnable;
    assign debugRegisterWriteAddress = destinationAddress;
    assign debugRegisterWriteData = registerWriteData;

endmodule
